maba_gentle_force:
  redis:
    host: 'redis:6379'
  limits:
    global:
      - max_usages: 10
        period: 1m
    listeners:
      - path: ^/
        limits_key: global
        identifiers: [ip]
      - path: ^/
        limits_key: global
        identifiers: [username]