version: '3'

services:
  php:
    build: .docker/php
    volumes:
    - ./:/var/api
    depends_on:
      - db
      - redis

  web:
    build: .docker/web
    ports:
    - 8080:80
    volumes:
      - ./.docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/api/public
    depends_on:
      - php

  db:
    image: mysql
    # These should not be used in production
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: secret


  redis:
    image: "redis:alpine"