name: Tests CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - name: Build the Docker images
      run: docker-compose build --build-arg USER_ID="$(id -u)" --build-arg GROUP_ID="$(id -g)"
    - name: Start the Docker containers
      run: docker-compose up -d
    - name: Validate composer file
      run: composer validate
    - name: Check requirements
      run: docker-compose exec -T --user user php composer check-platform-reqs
    - name: Install dependencies
      run: docker-compose exec -T --user user php composer install --no-progress --no-suggest --no-interaction
    - name: Generate oAuth keys
      run: |
        docker-compose exec -T --user user php mkdir -p var/keys
        docker-compose exec -T --user user php openssl genrsa -passout pass:'pick_a_really_strong_passphrase' -out var/keys/private.key 2048
        docker-compose exec -T --user user php openssl rsa -in var/keys/private.key -passin pass:'pick_a_really_strong_passphrase' -pubout -out var/keys/public.key
        docker-compose exec -T --user user php chmod 644 var/keys/private.key var/keys/public.key
        docker-compose exec -T --user user php pwd
        docker-compose exec -T --user user php ls -l
    - name: Prepare database
      run: |
        docker-compose exec -T --user user php php bin/console doctrine:migrations:migrate -n
        docker-compose exec -T --user user php php bin/console doctrine:fixtures:load -n
    - name: Create oAuth client
      run: docker-compose exec -T --user user php php bin/console trikoder:oauth2:create-client --grant-type=password --scope "testing profile:read" client_id client_secret -n
    - name: Check for security issues
      run: docker-compose exec -T --user user php symfony security:check
    - name: Run tests
      run: docker-compose exec -T --user user php php vendor/bin/simple-phpunit --testdox